# Generated by Django 4.0.1 on 2022-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, max_length=14, null=True)),
                ('show_phone_number', models.BooleanField(default=False)),
                ('second_phone_number', models.CharField(default=None, max_length=14, null=True)),
                ('show_second_phone_number', models.BooleanField(default=False)),
                ('office_phone_number', models.CharField(default=None, max_length=14, null=True)),
                ('show_office_phone_number', models.BooleanField(default=False)),
                ('office_address', models.CharField(default=None, max_length=256, null=True)),
                ('show_office_address', models.BooleanField(default=False)),
                ('email_address', models.CharField(default=None, max_length=100, null=True)),
                ('show_email_address', models.BooleanField(default=False)),
                ('facebook_link', models.CharField(default=None, max_length=256, null=True)),
                ('show_facebook_link', models.BooleanField(default=False)),
                ('twitter_link', models.CharField(default=None, max_length=256, null=True)),
                ('show_twitter_link', models.BooleanField(default=False)),
                ('youtube_link', models.CharField(default=None, max_length=256, null=True)),
                ('show_youtube_link', models.BooleanField(default=False)),
                ('linked_link', models.CharField(default=None, max_length=256, null=True)),
                ('show_linked_link', models.BooleanField(default=False)),
                ('instagram_link', models.CharField(default=None, max_length=256, null=True)),
                ('show_instagram_link', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_about_us',
            },
        ),
    ]
