# Generated by Django 4.0.1 on 2022-01-31 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_alter_aboutus_email_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us List'},
        ),
    ]
