# Generated by Django 4.0.1 on 2022-02-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_achievement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realtor',
            new_name='Agent',
        ),
        migrations.RenameModel(
            old_name='Listing',
            new_name='HomeListing',
        ),
    ]
