# Generated by Django 4.0.1 on 2022-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0011_rename_realtor_agent_rename_listing_homelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
